(cl:in-package infrastructure_msgs-msg)
(cl:export '(CURRENT_TIME-VAL
          CURRENT_TIME
          TOF-VAL
          TOF
          FSR1-VAL
          FSR1
          FSR2-VAL
          FSR2
          FSR3-VAL
          FSR3
          FSR4-VAL
          FSR4
          FSR5-VAL
          FSR5
          FSR6-VAL
          FSR6
          FSR7-VAL
          FSR7
          FSR8-VAL
          FSR8
          FSR9-VAL
          FSR9
          FSR10-VAL
          FSR10
          FSR11-VAL
          FSR11
          FSR12-VAL
          FSR12
          FSR_CONTACT_1-VAL
          FSR_CONTACT_1
          FSR_CONTACT_2-VAL
          FSR_CONTACT_2
))