; Auto-generated. Do not edit!


(cl:in-package infrastructure_msgs-msg)


;//! \htmlinclude DataCollectionResult.msg.html

(cl:defclass <DataCollectionResult> (roslisp-msg-protocol:ros-message)
  ((collection_stop
    :reader collection_stop
    :initarg :collection_stop
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DataCollectionResult (<DataCollectionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DataCollectionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DataCollectionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name infrastructure_msgs-msg:<DataCollectionResult> is deprecated: use infrastructure_msgs-msg:DataCollectionResult instead.")))

(cl:ensure-generic-function 'collection_stop-val :lambda-list '(m))
(cl:defmethod collection_stop-val ((m <DataCollectionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader infrastructure_msgs-msg:collection_stop-val is deprecated.  Use infrastructure_msgs-msg:collection_stop instead.")
  (collection_stop m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DataCollectionResult>) ostream)
  "Serializes a message object of type '<DataCollectionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'collection_stop) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DataCollectionResult>) istream)
  "Deserializes a message object of type '<DataCollectionResult>"
    (cl:setf (cl:slot-value msg 'collection_stop) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DataCollectionResult>)))
  "Returns string type for a message object of type '<DataCollectionResult>"
  "infrastructure_msgs/DataCollectionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DataCollectionResult)))
  "Returns string type for a message object of type 'DataCollectionResult"
  "infrastructure_msgs/DataCollectionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DataCollectionResult>)))
  "Returns md5sum for a message object of type '<DataCollectionResult>"
  "a92c4b50c6b16b340318f91aaaf7f2ff")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DataCollectionResult)))
  "Returns md5sum for a message object of type 'DataCollectionResult"
  "a92c4b50c6b16b340318f91aaaf7f2ff")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DataCollectionResult>)))
  "Returns full string definition for message of type '<DataCollectionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool collection_stop~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DataCollectionResult)))
  "Returns full string definition for message of type 'DataCollectionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool collection_stop~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DataCollectionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DataCollectionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DataCollectionResult
    (cl:cons ':collection_stop (collection_stop msg))
))
