; Auto-generated. Do not edit!


(cl:in-package infrastructure_msgs-msg)


;//! \htmlinclude StageResult.msg.html

(cl:defclass <StageResult> (roslisp-msg-protocol:ros-message)
  ((stage_result
    :reader stage_result
    :initarg :stage_result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass StageResult (<StageResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StageResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StageResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name infrastructure_msgs-msg:<StageResult> is deprecated: use infrastructure_msgs-msg:StageResult instead.")))

(cl:ensure-generic-function 'stage_result-val :lambda-list '(m))
(cl:defmethod stage_result-val ((m <StageResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader infrastructure_msgs-msg:stage_result-val is deprecated.  Use infrastructure_msgs-msg:stage_result instead.")
  (stage_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StageResult>) ostream)
  "Serializes a message object of type '<StageResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'stage_result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StageResult>) istream)
  "Deserializes a message object of type '<StageResult>"
    (cl:setf (cl:slot-value msg 'stage_result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StageResult>)))
  "Returns string type for a message object of type '<StageResult>"
  "infrastructure_msgs/StageResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StageResult)))
  "Returns string type for a message object of type 'StageResult"
  "infrastructure_msgs/StageResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StageResult>)))
  "Returns md5sum for a message object of type '<StageResult>"
  "e6d10aeffdd85028961e115279d59745")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StageResult)))
  "Returns md5sum for a message object of type 'StageResult"
  "e6d10aeffdd85028961e115279d59745")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StageResult>)))
  "Returns full string definition for message of type '<StageResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool stage_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StageResult)))
  "Returns full string definition for message of type 'StageResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool stage_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StageResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StageResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StageResult
    (cl:cons ':stage_result (stage_result msg))
))
