; Auto-generated. Do not edit!


(cl:in-package infrastructure_msgs-msg)


;//! \htmlinclude StageGoal.msg.html

(cl:defclass <StageGoal> (roslisp-msg-protocol:ros-message)
  ((stage_start
    :reader stage_start
    :initarg :stage_start
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass StageGoal (<StageGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StageGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StageGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name infrastructure_msgs-msg:<StageGoal> is deprecated: use infrastructure_msgs-msg:StageGoal instead.")))

(cl:ensure-generic-function 'stage_start-val :lambda-list '(m))
(cl:defmethod stage_start-val ((m <StageGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader infrastructure_msgs-msg:stage_start-val is deprecated.  Use infrastructure_msgs-msg:stage_start instead.")
  (stage_start m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StageGoal>) ostream)
  "Serializes a message object of type '<StageGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'stage_start) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StageGoal>) istream)
  "Deserializes a message object of type '<StageGoal>"
    (cl:setf (cl:slot-value msg 'stage_start) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StageGoal>)))
  "Returns string type for a message object of type '<StageGoal>"
  "infrastructure_msgs/StageGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StageGoal)))
  "Returns string type for a message object of type 'StageGoal"
  "infrastructure_msgs/StageGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StageGoal>)))
  "Returns md5sum for a message object of type '<StageGoal>"
  "6a64fcc91c8c3ea4155cd1503211cdea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StageGoal)))
  "Returns md5sum for a message object of type 'StageGoal"
  "6a64fcc91c8c3ea4155cd1503211cdea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StageGoal>)))
  "Returns full string definition for message of type '<StageGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool stage_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StageGoal)))
  "Returns full string definition for message of type 'StageGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool stage_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StageGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StageGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StageGoal
    (cl:cons ':stage_start (stage_start msg))
))
