; Auto-generated. Do not edit!


(cl:in-package infrastructure_msgs-msg)


;//! \htmlinclude StageFeedback.msg.html

(cl:defclass <StageFeedback> (roslisp-msg-protocol:ros-message)
  ((stage_status
    :reader stage_status
    :initarg :stage_status
    :type cl:string
    :initform ""))
)

(cl:defclass StageFeedback (<StageFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StageFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StageFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name infrastructure_msgs-msg:<StageFeedback> is deprecated: use infrastructure_msgs-msg:StageFeedback instead.")))

(cl:ensure-generic-function 'stage_status-val :lambda-list '(m))
(cl:defmethod stage_status-val ((m <StageFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader infrastructure_msgs-msg:stage_status-val is deprecated.  Use infrastructure_msgs-msg:stage_status instead.")
  (stage_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StageFeedback>) ostream)
  "Serializes a message object of type '<StageFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'stage_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'stage_status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StageFeedback>) istream)
  "Deserializes a message object of type '<StageFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'stage_status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'stage_status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StageFeedback>)))
  "Returns string type for a message object of type '<StageFeedback>"
  "infrastructure_msgs/StageFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StageFeedback)))
  "Returns string type for a message object of type 'StageFeedback"
  "infrastructure_msgs/StageFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StageFeedback>)))
  "Returns md5sum for a message object of type '<StageFeedback>"
  "44a8ac12072e758309ae673f423970a5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StageFeedback)))
  "Returns md5sum for a message object of type 'StageFeedback"
  "44a8ac12072e758309ae673f423970a5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StageFeedback>)))
  "Returns full string definition for message of type '<StageFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string stage_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StageFeedback)))
  "Returns full string definition for message of type 'StageFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string stage_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StageFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'stage_status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StageFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StageFeedback
    (cl:cons ':stage_status (stage_status msg))
))
