// Generated by gencpp from file infrastructure_msgs/DataCollectionFeedback.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONFEEDBACK_H
#define INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure_msgs
{
template <class ContainerAllocator>
struct DataCollectionFeedback_
{
  typedef DataCollectionFeedback_<ContainerAllocator> Type;

  DataCollectionFeedback_()
    : collection_status(false)  {
    }
  DataCollectionFeedback_(const ContainerAllocator& _alloc)
    : collection_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collection_status_type;
  _collection_status_type collection_status;





  typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DataCollectionFeedback_

typedef ::infrastructure_msgs::DataCollectionFeedback_<std::allocator<void> > DataCollectionFeedback;

typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionFeedback > DataCollectionFeedbackPtr;
typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionFeedback const> DataCollectionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.collection_status == rhs.collection_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acf07d06c46e58b681dd3667a811f384";
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacf07d06c46e58b6ULL;
  static const uint64_t static_value2 = 0x81dd3667a811f384ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure_msgs/DataCollectionFeedback";
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"bool collection_status\n"
"\n"
"\n"
;
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collection_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataCollectionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure_msgs::DataCollectionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "collection_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collection_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONFEEDBACK_H
