// Generated by gencpp from file infrastructure_msgs/DataCollectionGoal.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONGOAL_H
#define INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure_msgs
{
template <class ContainerAllocator>
struct DataCollectionGoal_
{
  typedef DataCollectionGoal_<ContainerAllocator> Type;

  DataCollectionGoal_()
    : collection_start(false)  {
    }
  DataCollectionGoal_(const ContainerAllocator& _alloc)
    : collection_start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collection_start_type;
  _collection_start_type collection_start;





  typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DataCollectionGoal_

typedef ::infrastructure_msgs::DataCollectionGoal_<std::allocator<void> > DataCollectionGoal;

typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionGoal > DataCollectionGoalPtr;
typedef boost::shared_ptr< ::infrastructure_msgs::DataCollectionGoal const> DataCollectionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.collection_start == rhs.collection_start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43648f36c0fa39dbf4a9583a1f3ed69d";
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43648f36c0fa39dbULL;
  static const uint64_t static_value2 = 0xf4a9583a1f3ed69dULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure_msgs/DataCollectionGoal";
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"bool collection_start\n"
;
  }

  static const char* value(const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collection_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataCollectionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure_msgs::DataCollectionGoal_<ContainerAllocator>& v)
  {
    s << indent << "collection_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collection_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MSGS_MESSAGE_DATACOLLECTIONGOAL_H
