// Generated by gencpp from file infrastructure_msgs/DataTimestamps.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MSGS_MESSAGE_DATATIMESTAMPS_H
#define INFRASTRUCTURE_MSGS_MESSAGE_DATATIMESTAMPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure_msgs
{
template <class ContainerAllocator>
struct DataTimestamps_
{
  typedef DataTimestamps_<ContainerAllocator> Type;

  DataTimestamps_()
    : trial_number(0)
    , collection_start_time()
    , collection_end_time()
    , total_time(0.0)  {
    }
  DataTimestamps_(const ContainerAllocator& _alloc)
    : trial_number(0)
    , collection_start_time()
    , collection_end_time()
    , total_time(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _trial_number_type;
  _trial_number_type trial_number;

   typedef ros::Time _collection_start_time_type;
  _collection_start_time_type collection_start_time;

   typedef ros::Time _collection_end_time_type;
  _collection_end_time_type collection_end_time;

   typedef double _total_time_type;
  _total_time_type total_time;





  typedef boost::shared_ptr< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> const> ConstPtr;

}; // struct DataTimestamps_

typedef ::infrastructure_msgs::DataTimestamps_<std::allocator<void> > DataTimestamps;

typedef boost::shared_ptr< ::infrastructure_msgs::DataTimestamps > DataTimestampsPtr;
typedef boost::shared_ptr< ::infrastructure_msgs::DataTimestamps const> DataTimestampsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator2> & rhs)
{
  return lhs.trial_number == rhs.trial_number &&
    lhs.collection_start_time == rhs.collection_start_time &&
    lhs.collection_end_time == rhs.collection_end_time &&
    lhs.total_time == rhs.total_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b7790f826e3d5970b2ea5a3e61bdd36";
  }

  static const char* value(const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b7790f826e3d597ULL;
  static const uint64_t static_value2 = 0x0b2ea5a3e61bdd36ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure_msgs/DataTimestamps";
  }

  static const char* value(const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 trial_number\n"
"time collection_start_time\n"
"time collection_end_time\n"
"float64 total_time\n"
;
  }

  static const char* value(const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trial_number);
      stream.next(m.collection_start_time);
      stream.next(m.collection_end_time);
      stream.next(m.total_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataTimestamps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure_msgs::DataTimestamps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure_msgs::DataTimestamps_<ContainerAllocator>& v)
  {
    s << indent << "trial_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.trial_number);
    s << indent << "collection_start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.collection_start_time);
    s << indent << "collection_end_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.collection_end_time);
    s << indent << "total_time: ";
    Printer<double>::stream(s, indent + "  ", v.total_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MSGS_MESSAGE_DATATIMESTAMPS_H
