// Generated by gencpp from file infrastructure_msgs/StageResult.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MSGS_MESSAGE_STAGERESULT_H
#define INFRASTRUCTURE_MSGS_MESSAGE_STAGERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure_msgs
{
template <class ContainerAllocator>
struct StageResult_
{
  typedef StageResult_<ContainerAllocator> Type;

  StageResult_()
    : stage_result(false)  {
    }
  StageResult_(const ContainerAllocator& _alloc)
    : stage_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stage_result_type;
  _stage_result_type stage_result;





  typedef boost::shared_ptr< ::infrastructure_msgs::StageResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure_msgs::StageResult_<ContainerAllocator> const> ConstPtr;

}; // struct StageResult_

typedef ::infrastructure_msgs::StageResult_<std::allocator<void> > StageResult;

typedef boost::shared_ptr< ::infrastructure_msgs::StageResult > StageResultPtr;
typedef boost::shared_ptr< ::infrastructure_msgs::StageResult const> StageResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure_msgs::StageResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure_msgs::StageResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure_msgs::StageResult_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::StageResult_<ContainerAllocator2> & rhs)
{
  return lhs.stage_result == rhs.stage_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure_msgs::StageResult_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::StageResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::StageResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::StageResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::StageResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6d10aeffdd85028961e115279d59745";
  }

  static const char* value(const ::infrastructure_msgs::StageResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6d10aeffdd85028ULL;
  static const uint64_t static_value2 = 0x961e115279d59745ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure_msgs/StageResult";
  }

  static const char* value(const ::infrastructure_msgs::StageResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"bool stage_result\n"
;
  }

  static const char* value(const ::infrastructure_msgs::StageResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stage_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure_msgs::StageResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure_msgs::StageResult_<ContainerAllocator>& v)
  {
    s << indent << "stage_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stage_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MSGS_MESSAGE_STAGERESULT_H
