// Generated by gencpp from file infrastructure_msgs/StageGoal.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MSGS_MESSAGE_STAGEGOAL_H
#define INFRASTRUCTURE_MSGS_MESSAGE_STAGEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure_msgs
{
template <class ContainerAllocator>
struct StageGoal_
{
  typedef StageGoal_<ContainerAllocator> Type;

  StageGoal_()
    : stage_start(false)  {
    }
  StageGoal_(const ContainerAllocator& _alloc)
    : stage_start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stage_start_type;
  _stage_start_type stage_start;





  typedef boost::shared_ptr< ::infrastructure_msgs::StageGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure_msgs::StageGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StageGoal_

typedef ::infrastructure_msgs::StageGoal_<std::allocator<void> > StageGoal;

typedef boost::shared_ptr< ::infrastructure_msgs::StageGoal > StageGoalPtr;
typedef boost::shared_ptr< ::infrastructure_msgs::StageGoal const> StageGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure_msgs::StageGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure_msgs::StageGoal_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::StageGoal_<ContainerAllocator2> & rhs)
{
  return lhs.stage_start == rhs.stage_start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure_msgs::StageGoal_<ContainerAllocator1> & lhs, const ::infrastructure_msgs::StageGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure_msgs::StageGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure_msgs::StageGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure_msgs::StageGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a64fcc91c8c3ea4155cd1503211cdea";
  }

  static const char* value(const ::infrastructure_msgs::StageGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a64fcc91c8c3ea4ULL;
  static const uint64_t static_value2 = 0x155cd1503211cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure_msgs/StageGoal";
  }

  static const char* value(const ::infrastructure_msgs::StageGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"bool stage_start\n"
;
  }

  static const char* value(const ::infrastructure_msgs::StageGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stage_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure_msgs::StageGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure_msgs::StageGoal_<ContainerAllocator>& v)
  {
    s << indent << "stage_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stage_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MSGS_MESSAGE_STAGEGOAL_H
