// Auto-generated. Do not edit!

// (in-package infrastructure_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DataCollectionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.collection_start = null;
    }
    else {
      if (initObj.hasOwnProperty('collection_start')) {
        this.collection_start = initObj.collection_start
      }
      else {
        this.collection_start = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DataCollectionGoal
    // Serialize message field [collection_start]
    bufferOffset = _serializer.bool(obj.collection_start, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DataCollectionGoal
    let len;
    let data = new DataCollectionGoal(null);
    // Deserialize message field [collection_start]
    data.collection_start = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'infrastructure_msgs/DataCollectionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '43648f36c0fa39dbf4a9583a1f3ed69d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    bool collection_start
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DataCollectionGoal(null);
    if (msg.collection_start !== undefined) {
      resolved.collection_start = msg.collection_start;
    }
    else {
      resolved.collection_start = false
    }

    return resolved;
    }
};

module.exports = DataCollectionGoal;
