// Auto-generated. Do not edit!

// (in-package infrastructure_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DataCollectionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.collection_status = null;
    }
    else {
      if (initObj.hasOwnProperty('collection_status')) {
        this.collection_status = initObj.collection_status
      }
      else {
        this.collection_status = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DataCollectionFeedback
    // Serialize message field [collection_status]
    bufferOffset = _serializer.bool(obj.collection_status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DataCollectionFeedback
    let len;
    let data = new DataCollectionFeedback(null);
    // Deserialize message field [collection_status]
    data.collection_status = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'infrastructure_msgs/DataCollectionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'acf07d06c46e58b681dd3667a811f384';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    bool collection_status
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DataCollectionFeedback(null);
    if (msg.collection_status !== undefined) {
      resolved.collection_status = msg.collection_status;
    }
    else {
      resolved.collection_status = false
    }

    return resolved;
    }
};

module.exports = DataCollectionFeedback;
