// Auto-generated. Do not edit!

// (in-package infrastructure_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StageResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.stage_result = null;
    }
    else {
      if (initObj.hasOwnProperty('stage_result')) {
        this.stage_result = initObj.stage_result
      }
      else {
        this.stage_result = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StageResult
    // Serialize message field [stage_result]
    bufferOffset = _serializer.bool(obj.stage_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StageResult
    let len;
    let data = new StageResult(null);
    // Deserialize message field [stage_result]
    data.stage_result = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'infrastructure_msgs/StageResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e6d10aeffdd85028961e115279d59745';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    bool stage_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StageResult(null);
    if (msg.stage_result !== undefined) {
      resolved.stage_result = msg.stage_result;
    }
    else {
      resolved.stage_result = false
    }

    return resolved;
    }
};

module.exports = StageResult;
