// Auto-generated. Do not edit!

// (in-package infrastructure_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StageGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.stage_start = null;
    }
    else {
      if (initObj.hasOwnProperty('stage_start')) {
        this.stage_start = initObj.stage_start
      }
      else {
        this.stage_start = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StageGoal
    // Serialize message field [stage_start]
    bufferOffset = _serializer.bool(obj.stage_start, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StageGoal
    let len;
    let data = new StageGoal(null);
    // Deserialize message field [stage_start]
    data.stage_start = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'infrastructure_msgs/StageGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6a64fcc91c8c3ea4155cd1503211cdea';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    bool stage_start
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StageGoal(null);
    if (msg.stage_start !== undefined) {
      resolved.stage_start = msg.stage_start;
    }
    else {
      resolved.stage_start = false
    }

    return resolved;
    }
};

module.exports = StageGoal;
