// Generated by gencpp from file kinova_scripts/Joint_anglesRequest.msg
// DO NOT EDIT!


#ifndef KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESREQUEST_H
#define KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinova_scripts
{
template <class ContainerAllocator>
struct Joint_anglesRequest_
{
  typedef Joint_anglesRequest_<ContainerAllocator> Type;

  Joint_anglesRequest_()
    : angles()  {
    }
  Joint_anglesRequest_(const ContainerAllocator& _alloc)
    : angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_anglesRequest_

typedef ::kinova_scripts::Joint_anglesRequest_<std::allocator<void> > Joint_anglesRequest;

typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesRequest > Joint_anglesRequestPtr;
typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesRequest const> Joint_anglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator1> & lhs, const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator1> & lhs, const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_scripts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7ca77b9da2dfe623a276e10b570d2df";
  }

  static const char* value(const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7ca77b9da2dfe62ULL;
  static const uint64_t static_value2 = 0x3a276e10b570d2dfULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_scripts/Joint_anglesRequest";
  }

  static const char* value(const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# inputs\n"
"float64[] angles\n"
;
  }

  static const char* value(const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_anglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_scripts::Joint_anglesRequest_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESREQUEST_H
