// Generated by gencpp from file kinova_scripts/Joint_anglesResponse.msg
// DO NOT EDIT!


#ifndef KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESRESPONSE_H
#define KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinova_scripts
{
template <class ContainerAllocator>
struct Joint_anglesResponse_
{
  typedef Joint_anglesResponse_<ContainerAllocator> Type;

  Joint_anglesResponse_()
    : success(false)  {
    }
  Joint_anglesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_anglesResponse_

typedef ::kinova_scripts::Joint_anglesResponse_<std::allocator<void> > Joint_anglesResponse;

typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesResponse > Joint_anglesResponsePtr;
typedef boost::shared_ptr< ::kinova_scripts::Joint_anglesResponse const> Joint_anglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator1> & lhs, const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator1> & lhs, const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_scripts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_scripts/Joint_anglesResponse";
  }

  static const char* value(const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# outputs\n"
"bool success\n"
;
  }

  static const char* value(const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_anglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_scripts::Joint_anglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLESRESPONSE_H
