// Generated by gencpp from file kinova_scripts/Joint_angles.msg
// DO NOT EDIT!


#ifndef KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLES_H
#define KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLES_H

#include <ros/service_traits.h>


#include <kinova_scripts/Joint_anglesRequest.h>
#include <kinova_scripts/Joint_anglesResponse.h>


namespace kinova_scripts
{

struct Joint_angles
{

typedef Joint_anglesRequest Request;
typedef Joint_anglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Joint_angles
} // namespace kinova_scripts


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_scripts::Joint_angles > {
  static const char* value()
  {
    return "33d1484c959ed2edcc0fb37067e64ed1";
  }

  static const char* value(const ::kinova_scripts::Joint_angles&) { return value(); }
};

template<>
struct DataType< ::kinova_scripts::Joint_angles > {
  static const char* value()
  {
    return "kinova_scripts/Joint_angles";
  }

  static const char* value(const ::kinova_scripts::Joint_angles&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_scripts::Joint_anglesRequest> should match
// service_traits::MD5Sum< ::kinova_scripts::Joint_angles >
template<>
struct MD5Sum< ::kinova_scripts::Joint_anglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_scripts::Joint_angles >::value();
  }
  static const char* value(const ::kinova_scripts::Joint_anglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_scripts::Joint_anglesRequest> should match
// service_traits::DataType< ::kinova_scripts::Joint_angles >
template<>
struct DataType< ::kinova_scripts::Joint_anglesRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_scripts::Joint_angles >::value();
  }
  static const char* value(const ::kinova_scripts::Joint_anglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_scripts::Joint_anglesResponse> should match
// service_traits::MD5Sum< ::kinova_scripts::Joint_angles >
template<>
struct MD5Sum< ::kinova_scripts::Joint_anglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_scripts::Joint_angles >::value();
  }
  static const char* value(const ::kinova_scripts::Joint_anglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_scripts::Joint_anglesResponse> should match
// service_traits::DataType< ::kinova_scripts::Joint_angles >
template<>
struct DataType< ::kinova_scripts::Joint_anglesResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_scripts::Joint_angles >::value();
  }
  static const char* value(const ::kinova_scripts::Joint_anglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_SCRIPTS_MESSAGE_JOINT_ANGLES_H
