// Generated by gencpp from file kinova_scripts/New_pose.msg
// DO NOT EDIT!


#ifndef KINOVA_SCRIPTS_MESSAGE_NEW_POSE_H
#define KINOVA_SCRIPTS_MESSAGE_NEW_POSE_H

#include <ros/service_traits.h>


#include <kinova_scripts/New_poseRequest.h>
#include <kinova_scripts/New_poseResponse.h>


namespace kinova_scripts
{

struct New_pose
{

typedef New_poseRequest Request;
typedef New_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct New_pose
} // namespace kinova_scripts


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_scripts::New_pose > {
  static const char* value()
  {
    return "4594a58ce1af583f94fa685100bbf914";
  }

  static const char* value(const ::kinova_scripts::New_pose&) { return value(); }
};

template<>
struct DataType< ::kinova_scripts::New_pose > {
  static const char* value()
  {
    return "kinova_scripts/New_pose";
  }

  static const char* value(const ::kinova_scripts::New_pose&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_scripts::New_poseRequest> should match
// service_traits::MD5Sum< ::kinova_scripts::New_pose >
template<>
struct MD5Sum< ::kinova_scripts::New_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_scripts::New_pose >::value();
  }
  static const char* value(const ::kinova_scripts::New_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_scripts::New_poseRequest> should match
// service_traits::DataType< ::kinova_scripts::New_pose >
template<>
struct DataType< ::kinova_scripts::New_poseRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_scripts::New_pose >::value();
  }
  static const char* value(const ::kinova_scripts::New_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_scripts::New_poseResponse> should match
// service_traits::MD5Sum< ::kinova_scripts::New_pose >
template<>
struct MD5Sum< ::kinova_scripts::New_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_scripts::New_pose >::value();
  }
  static const char* value(const ::kinova_scripts::New_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_scripts::New_poseResponse> should match
// service_traits::DataType< ::kinova_scripts::New_pose >
template<>
struct DataType< ::kinova_scripts::New_poseResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_scripts::New_pose >::value();
  }
  static const char* value(const ::kinova_scripts::New_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_SCRIPTS_MESSAGE_NEW_POSE_H
