// Generated by gencpp from file kinova_scripts/New_poseRequest.msg
// DO NOT EDIT!


#ifndef KINOVA_SCRIPTS_MESSAGE_NEW_POSEREQUEST_H
#define KINOVA_SCRIPTS_MESSAGE_NEW_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinova_scripts
{
template <class ContainerAllocator>
struct New_poseRequest_
{
  typedef New_poseRequest_<ContainerAllocator> Type;

  New_poseRequest_()
    : pose()  {
    }
  New_poseRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::kinova_scripts::New_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_scripts::New_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct New_poseRequest_

typedef ::kinova_scripts::New_poseRequest_<std::allocator<void> > New_poseRequest;

typedef boost::shared_ptr< ::kinova_scripts::New_poseRequest > New_poseRequestPtr;
typedef boost::shared_ptr< ::kinova_scripts::New_poseRequest const> New_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_scripts::New_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_scripts::New_poseRequest_<ContainerAllocator1> & lhs, const ::kinova_scripts::New_poseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_scripts::New_poseRequest_<ContainerAllocator1> & lhs, const ::kinova_scripts::New_poseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_scripts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_scripts::New_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_scripts::New_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_scripts::New_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76249fb45cba333e6a82c7f91cfe1879";
  }

  static const char* value(const ::kinova_scripts::New_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76249fb45cba333eULL;
  static const uint64_t static_value2 = 0x6a82c7f91cfe1879ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_scripts/New_poseRequest";
  }

  static const char* value(const ::kinova_scripts::New_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# inputs\n"
"float64[] pose\n"
;
  }

  static const char* value(const ::kinova_scripts::New_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct New_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_scripts::New_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_scripts::New_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_SCRIPTS_MESSAGE_NEW_POSEREQUEST_H
