// Generated by gencpp from file arm_tracking/PidParam.msg
// DO NOT EDIT!


#ifndef ARM_TRACKING_MESSAGE_PIDPARAM_H
#define ARM_TRACKING_MESSAGE_PIDPARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_tracking
{
template <class ContainerAllocator>
struct PidParam_
{
  typedef PidParam_<ContainerAllocator> Type;

  PidParam_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
    }
  PidParam_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::arm_tracking::PidParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_tracking::PidParam_<ContainerAllocator> const> ConstPtr;

}; // struct PidParam_

typedef ::arm_tracking::PidParam_<std::allocator<void> > PidParam;

typedef boost::shared_ptr< ::arm_tracking::PidParam > PidParamPtr;
typedef boost::shared_ptr< ::arm_tracking::PidParam const> PidParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_tracking::PidParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_tracking::PidParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_tracking::PidParam_<ContainerAllocator1> & lhs, const ::arm_tracking::PidParam_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_tracking::PidParam_<ContainerAllocator1> & lhs, const ::arm_tracking::PidParam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_tracking::PidParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_tracking::PidParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_tracking::PidParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_tracking::PidParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_tracking::PidParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_tracking::PidParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_tracking::PidParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "972f4074b1c05b4e6ef321f04d38ec3f";
  }

  static const char* value(const ::arm_tracking::PidParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x972f4074b1c05b4eULL;
  static const uint64_t static_value2 = 0x6ef321f04d38ec3fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_tracking::PidParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_tracking/PidParam";
  }

  static const char* value(const ::arm_tracking::PidParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_tracking::PidParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 kp\n"
"float64 ki\n"
"float64 kd\n"
;
  }

  static const char* value(const ::arm_tracking::PidParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_tracking::PidParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PidParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_tracking::PidParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_tracking::PidParam_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_TRACKING_MESSAGE_PIDPARAM_H
